services:

  oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: campuslab-oracle
    restart: unless-stopped

    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}

    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./oracle/init:/container-entrypoint-initdb.d

    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 240s

    networks:
      - campuslab-network


  catalog:
    build:
      context: ../ms-campuslab-catalog
      dockerfile: Dockerfile

    container_name: campuslab-catalog
    restart: unless-stopped

    environment:
      SERVER_PORT: 8082

      DB_URL: jdbc:oracle:thin:@oracle:1521/FREEPDB1
      DB_USERNAME: CAMPUSLAB_CATALOG
      DB_PASSWORD: ${CATALOG_DB_PASSWORD}

      DDL_AUTO: update
      SHOW_SQL: false

    depends_on:
      oracle:
        condition: service_healthy

    networks:
      - campuslab-network


  bookings:
    build:
      context: ../ms-campuslab-bookings
      dockerfile: Dockerfile

    container_name: campuslab-bookings
    restart: unless-stopped

    environment:
      SERVER_PORT: 8081

      DB_URL: jdbc:oracle:thin:@oracle:1521/FREEPDB1
      DB_USERNAME: CAMPUSLAB_BOOKINGS
      DB_PASSWORD: ${BOOKINGS_DB_PASSWORD}

      DDL_AUTO: update
      SHOW_SQL: false

    depends_on:
      oracle:
        condition: service_healthy

    networks:
      - campuslab-network
  
  report:
    build:
      context: ../ms-campuslab-report
    container_name: campuslab-report
    environment:
      SERVER_PORT: 8084
      BOOKINGS_SERVICE_URL: http://bookings:8081
      CATALOG_SERVICE_URL: http://catalog:8082
    depends_on:
      - bookings
      - catalog
    networks:
      - campuslab-network

  audit:
    build:
      context: ../ms-campuslab-audit
    container_name: campuslab-audit
    environment:
      SERVER_PORT: 8085
      DB_URL: jdbc:oracle:thin:@oracle:1521/FREEPDB1
      DB_USERNAME: CAMPUSLAB_AUDIT
      DB_PASSWORD: ${AUDIT_DB_PASSWORD}
    depends_on:
      oracle:
        condition: service_healthy
    networks:
      - campuslab-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: campuslab-rabbitmq
    restart: unless-stopped

    environment:
    RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
    RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

    ports:
    - "15672:15672"
    networks:
    - campuslab-network


  notify:
    build:
      context: ../ms-campuslab-notify
      dockerfile: Dockerfile

    container_name: campuslab-notify
    restart: unless-stopped

    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

    depends_on:
      - rabbitmq

    networks:
      - campuslab-network


  bff:
    build:
      context: ../ms-campuslab-bff
      dockerfile: Dockerfile

    container_name: campuslab-bff
    restart: unless-stopped

    environment:
      SERVER_PORT: 8080

      AZURE_ISSUER_URI: ${AZURE_ISSUER_URI}
      AZURE_AUDIENCE: ${AZURE_AUDIENCE}

      CATALOG_SERVICE_URL: http://catalog:8082
      BOOKINGS_SERVICE_URL: http://bookings:8081
      REPORT_SERVICE_URL: http://report:8084
      AUDIT_SERVICE_URL: http://audit:8085

    depends_on:
      - catalog
      - bookings
      - report
      - audit

    ports:
      - "8080:8080"

    networks:
      - campuslab-network


volumes:
  oracle-data:


networks:
  campuslab-network:
    driver: bridge