services:

  oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: campuslab-oracle
    restart: unless-stopped

    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${ORACLE_APP_USER}
      APP_USER_PASSWORD: ${ORACLE_APP_PASSWORD}

    ports:
      - "1521:1521"

    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./oracle/init:/container-entrypoint-initdb.d

volumes:
  oracle-data: