ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER CAMPUSLAB_CATALOG IDENTIFIED BY Catalog123;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO CAMPUSLAB_CATALOG;
ALTER USER CAMPUSLAB_CATALOG QUOTA UNLIMITED ON USERS;

CREATE USER CAMPUSLAB_BOOKINGS IDENTIFIED BY Bookings123;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO CAMPUSLAB_BOOKINGS;
ALTER USER CAMPUSLAB_BOOKINGS QUOTA UNLIMITED ON USERS;