CREATE USER CAMPUSLAB_CATALOG IDENTIFIED BY catalog_password;
GRANT CONNECT, RESOURCE TO CAMPUSLAB_CATALOG;
ALTER USER CAMPUSLAB_CATALOG QUOTA UNLIMITED ON USERS;

CREATE USER CAMPUSLAB_BOOKINGS IDENTIFIED BY bookings_password;
GRANT CONNECT, RESOURCE TO CAMPUSLAB_BOOKINGS;
ALTER USER CAMPUSLAB_BOOKINGS QUOTA UNLIMITED ON USERS;